# SPDX-FileCopyrightText: 2026 - GitHub user: fredericks1982
# SPDX-License-Identifier: Apache-2.0

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "Repository maintenance scheduled tasks"

on:
  schedule:
    - cron: "33 7 26 * *"
  workflow_dispatch:

# Define exact minimal required permissions
permissions:
  contents: none # Doesn't need content access
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: project-maintenance-jobs

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Apply stale policy
        uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          days-before-stale: 90
          stale-issue-message: >
            This item has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          stale-pr-message: >
            There hasn't been any activity on this item recently. This pull request has
            been automatically marked as stale because of that and will be closed if no
            further activity occurs. Thank you for contributions.
